"""create_catalogue_tables

Revision ID: 157545fb2587
Revises: 7c0ba638471e
Create Date: 2026-09-05 20:39:10.360949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '157545fb2587'
down_revision: Union[str, Sequence[str], None] = '7c0ba638471e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_parent'), ['parent'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_parent'), ['parent'], unique=False)

    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_types_title'), ['title'], unique=False)

    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_type'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attributes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_attributes_product_type'), ['product_type'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['type'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_upc'), ['upc'], unique=True)

    op.create_table('product_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_attribute', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_attribute'], ['product_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_attribute_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attribute_values_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_attribute_values_product_attribute'), ['product_attribute'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_attribute_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attribute_values_product_attribute'))
        batch_op.drop_index(batch_op.f('ix_product_attribute_values_product'))

    op.drop_table('product_attribute_values')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_upc'))
        batch_op.drop_index(batch_op.f('ix_products_type'))
        batch_op.drop_index(batch_op.f('ix_products_title'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attributes_product_type'))
        batch_op.drop_index(batch_op.f('ix_product_attributes_name'))

    op.drop_table('product_attributes')
    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_types_title'))

    op.drop_table('product_types')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_parent'))
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
